APP_PASSWORD = "w0rdpass"
OPENAI_API_KEY = "sk-..."
XAI_API_KEY = "xai-rNsxvlLpMj8mJ7E5Hk3HD8LpO5telBlONhw4PPxEYOtq2RRYt7Pnxjs1olMmOM7EZkbSKFYxvwB0RQnX"
DEEPSEEK_API_KEY = "sk-d3a88a6eee384ca3b2be6ca20ccff40f"
